import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, Clock, Calendar, Heart, Laugh, Users } from "lucide-react";

export const metadata: Metadata = {
  title: "Humor and Compatibility: The Best Sync | SyncOrSink",
  description: "Why does a shared sense of humor define a friendship? Explore the link between humor, synchronicity, and why a SyncOrSink roast is so accurate.",
};

export default function HumorArticle() {
  return (
    <main className="flex-1 w-full max-w-4xl mx-auto px-6 py-16 md:py-24">
      <article className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-1000">
        <Link href="/articles" className="inline-flex items-center gap-2 text-slate-500 hover:text-primary transition-colors font-medium">
          <ArrowLeft className="w-4 h-4" />
          Back to Articles
        </Link>

        <header className="space-y-6">
          <div className="flex flex-wrap items-center gap-4 text-sm font-medium text-slate-500">
            <span className="px-3 py-1 rounded-full bg-accent/10 text-accent border border-accent/20 uppercase tracking-widest text-[10px] font-bold">Relationships</span>
            <div className="flex items-center gap-1.5 leading-none">
              <Calendar className="w-4 h-4" />
              April 22, 2026
            </div>
            <div className="flex items-center gap-1.5 leading-none">
              <Clock className="w-4 h-4" />
              5 min read
            </div>
          </div>
          <h1 className="text-4xl md:text-6xl font-black text-white tracking-tight leading-[1.1]">
            Humor and Compatibility: Why Shared Laughter is the Best <span className="text-accent">Sync</span>
          </h1>
          <p className="text-xl text-slate-400 leading-relaxed italic border-l-4 border-slate-800 pl-6">
            If you can laugh together at a 10-second panic choice, you can survive anything.
          </p>
        </header>

        <div className="prose prose-invert prose-slate max-w-none space-y-10">
          <section className="space-y-4">
            <p className="text-lg text-slate-300 leading-relaxed">
              We often talk about compatibility in terms of shared interests or life goals. But for day-to-day friendship, nothing matters more than your &quot;humor sync.&quot; A shared sense of humor acts as a social lubricant, a stress-reliever, and a secret language between friends.
            </p>
            <p className="text-lg text-slate-300 leading-relaxed">
              At <span className="text-white font-bold">SyncOrSink</span>, we believe that the most honest humor comes out under pressure. Here&apos;s why your sense of humor is the ultimate compatibility test.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-bold text-white flex items-center gap-3">
              <Laugh className="text-accent w-8 h-8" />
              1. Humor as a Shared Worldview
            </h2>
            <p className="text-slate-300 leading-relaxed">
              What someone finds funny says a lot about how they see the world. If you both find the same absurd &quot;Would You Rather&quot; prompt hilarious, it means you share a frame of reference. You see the same incongruities and the same ironies in life. This shared worldview is the bedrock of a &quot;Soul Sync&quot; score.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-bold text-white flex items-center gap-3">
              <Heart className="text-danger w-8 h-8" />
              2. Vulnerability and the Roast
            </h2>
            <p className="text-slate-300 leading-relaxed">
              Laughter requires a level of vulnerability. To laugh at yourself—or at a roast generated by an AI—you need to be comfortable with your own imperfections. Friends who can roast each other and laugh about it have higher levels of trust. This is why the results page of SyncOrSink is often where the most bonding happens.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-bold text-white flex items-center gap-3">
              <Users className="text-primary w-8 h-8" />
              3. The Science of the Inside Joke
            </h2>
            <p className="text-slate-300 leading-relaxed">
              Every round of SyncOrSink has the potential to create a new inside joke. Whether it&apos;s a bizarre combination of answers or a particularly cutting roast, these shared moments of humor build a unique history between friends. It&apos;s these small, hilarious data points that differentiate a casual acquaintance from a best friend.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl font-bold text-white mb-4">Finding Your Synchronicity</h2>
            <p className="text-slate-300 leading-relaxed">
              Next time you play SyncOrSink, don&apos;t just look at the percentage. Listen to the laughter that happens during and after the round. That sound is the real measure of your friendship.
            </p>
          </section>

          <section className="pt-8 border-t border-slate-800 text-center">
            <h3 className="text-2xl font-bold text-white mb-6">Ready to see if your humor matches?</h3>
            <Link href="/multiplayer" className="inline-block bg-accent text-slate-900 font-bold px-8 py-4 rounded-2xl hover:scale-105 transition-transform">
              Test Your Humor Sync
            </Link>
          </section>
        </div>
      </article>
    </main>
  );
}
